version: '3.8'

networks:
  ck-io:

services:
  nexus:
    image: sonatype/nexus3:3.38.1
    container_name: 'nexus'
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - './volumes/nexus-data:/nexus-data'
    networks:
      - ck-io
